# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{ 
  "username": "test",
  "password": "secret"
}
###
@token = {{login.response.body.access_token}}
GET http://localhost:3000/statistics
Authorization: Bearer {{token}}

###
GET http://localhost:3000/statistics/on-contract
Authorization: Bearer {{token}}

###
GET http://localhost:3000/statistics/department
Authorization: Bearer {{token}}

###
GET http://localhost:3000/statistics/sub-department
Authorization: Bearer {{token}}